# Generated by Django 3.2 on 2021-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(default='store', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='store',
            field=models.CharField(max_length=10),
        ),
    ]
