# Generated by Django 3.2 on 2021-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
