# Generated by Django 3.2 on 2021-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_sales_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Seafood', 'Seafood'), ('Beauty', 'Beauty'), ('Wine, Beer & Spirits', 'Wine, Beer & Spirits'), ('Meat', 'Meat')], max_length=200),
        ),
    ]
