# Generated by Django 3.2 on 2021-11-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211129_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marriage',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=200, null=True),
        ),
    ]
