# Generated by Django 3.2 on 2021-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_marriage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='title',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Store Manager', 'Store Manager'), ('Region Manager', 'Region Manager')], max_length=200),
        ),
    ]
